### ISSUE TITLE
TOP-Data not completely shown in Grafana

### ISSUE THREAD

**Issue by ukedk** [adejoux/nmon2influxdb#22] opened 2016-06-28 16:11 UTC
Hello Alain,
thank you very much for providing us nmon2influxdb! It workes very fine! One little question: We have a large System where we want to import the TOP-Data. nmon2influxdb import worked without errors. But on the generated dashboard the Graph is incompletly drawn. (only on part in the middle of the graph) Checking the nmon-file against pgraph the data is correctly reported. Is there a possibility to do some debugging ? Or do you have some idea for that behaviour ?  I checked influxdb.log/grafana.log without success. 
Thank you in advance !

P.S. "click" on a Process-Name in the footer of the TOP-Graph displays the process correctly over the complete timewindow. It seems the "stacked" Start-Graph is not 100% correct.

**Comment by adejoux** [comment] 2016-06-29 07:20
Hello,

Thanks for your feedbacks. 

To be honest I am still struggling on how to display properly the processes in TOP on large systems. One entry can contains hundreds of processes. It's why I disabled it by default.

Can you share your nmon file with me ? I will try pgraph to see how they sort the problem and try to do the same thing in grafana. 

PS: You can remove server name and filesystems informations from the nmon file if you want to share it anonymised. 

Send it to me by email or drop it here like you prefer.

Alain

**Comment by ukedk** [comment] 2016-06-29 10:30
Hi! sorry... I can´t find any mail adress. Do you have a public one ? or could you write to ulrich.kiefer([at])hornbach.com ? I would send you a reply with the modified nmon-file.

**Comment by adejoux** [comment] 2016-06-29 18:19
Thanks for your nmon file.

I think I reproduced your problem:
![image](https://cloud.githubusercontent.com/assets/741174/16463403/fb093bf0-3e35-11e6-9654-aa2422dfee35.png)

It's because some processes can disappear and it's making stacking difficult like smbd in your file:
![image](https://cloud.githubusercontent.com/assets/741174/16463518/712c6fc8-3e36-11e6-843b-99381f3170d8.png)

Disabling stacking give the same kind of output than pgraph:
![image](https://cloud.githubusercontent.com/assets/741174/16463572/a65e16e2-3e36-11e6-91e3-2b1429bff13b.png)

![image](https://cloud.githubusercontent.com/assets/741174/16463545/88934cc2-3e36-11e6-8a8c-ebc561872497.png)

Did you care about stacking the processes in the view?

**Comment by adejoux** [comment] 2016-06-30 20:14
New TOP panel:
![image](https://cloud.githubusercontent.com/assets/741174/16502670/d9cbfe66-3f0f-11e6-933b-90ea288bbb2f.png)
It's summing the processes with same name instead of averaging them and different processes are not stacked anymore(was not working anyway).

**Comment by ukedk** [comment] 2016-07-01 07:38
Hello!
It looks very fine now. Thanks a lot for very fast help.
I am not in Office today. So I will Update on Monday.
Greetings
Ulrich 

Am 30. Juni 2016 22:14:06 MESZ, schrieb adejoux notifications@github.com:

> New TOP panel:
> ![image](https://cloud.githubusercontent.com/assets/741174/16502670/d9cbfe66-3f0f-11e6-933b-90ea288bbb2f.png)
> It's summing the processes with same name instead of averaging them and
> different processes are not stacked anymore(was not working anyway).
> 
> ---
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/adejoux/nmon2influxdb/issues/22#issuecomment-229774815

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by adejoux** [comment] 2016-07-04 13:29
Thanks for the feedback :)

Closing the issue.

**Closed as completed by adejoux** 2016-07-04 13:29 UTC
