### ISSUE TITLE
Configuration File Location /etc/nmon2influxdb

### ISSUE THREAD

**Issue by awilson77584** [adejoux/nmon2influxdb#35] opened 2016-12-05 20:40 UTC
Is is feasible to move the configuration file to the /etc directory? Perhaps in an /etc/nmon2influxdb directory?

**Comment by adejoux** [comment] 2016-12-05 20:56
Hello,

I planned to add this feature with my reworking of the configuration. I would like to add a config sub command. It will permit me to manage encrypted password properly. 

But I am not sure when I will code it :) So let's add first this quick to implement change :)

Thanks,

Alain

**Comment by adejoux** [comment] 2016-12-10 10:36
Support for /etc/nmon2influxdb/nmon2influxdb.cfg added. It's first checking if it's present before checking home directory.

Closing.

Alain

**Comment by awilson77584** [comment] 2016-12-14 22:34
Hi Alain.  I get an error message about failed authentication when using /etc/nmon2influxdb.cfg even with the import ssh-related values commented out.  I executed nmon2influxdb import *.nmon in a local directory and get the authentication error.  I did rm the zero byte ~/.nmon2influxdb.cfg in that test.  Is it required? 

When using a ~/.nmon2influxdb.cfg file, everything functions normally.

Another question, when we use debug = true, where are the log files stored?

Thanks!

**Comment by adejoux** [comment] 2016-12-15 20:07
Hello,

It's really really strange. I couldn't reproduce the problem. 

The debugging for now is not useful. I opened issue #37. I will improve it during this weekend and provide you a version allowing a better debug. To see what happens.

Thanks,

Alain

**Comment by awilson77584** [comment] 2016-12-16 18:53
Thanks!

**Comment by adejoux** [comment] 2017-01-05 21:01
Hello,

I didn't finish my new debug mechanism but I improved the existing one. Could you test with version [2.1.1](https://github.com/adejoux/nmon2influxdb/releases/tag/v2.1.1). in debug mode.

It will start with a section like that: 

```
configuration: &{Debug:true Timezone:Europe/Paris InfluxdbUser:root InfluxdbPassword:root InfluxdbServer:localhost InfluxdbPort:8086 InfluxdbDatabase:nmon_reports GrafanaUser: GrafanaPassword: GrafanaURL: GrafanaAccess: GrafanaDatasource: HMCServer: HMCUser: HMCPassword: HMCDatabase:nmon2influxdbHMC HMCDataRetention: HMCManagedSystem: HMCManagedSystemOnly:false HMCSamples:0 ImportSkipDisks:false ImportAllCpus:false ImportBuildDashboard:false ImportForce:false ImportSkipMetrics:JFSINODE|TOP|PCPU ImportLogDatabase:nmon2influxdb_log ImportLogRetention:2d ImportDataRetention: ImportSSHUser:adejoux ImportSSHKey:/home/adejoux/.ssh/id_rsa DashboardWriteFile:false StatsLimit:0 StatsSort:mean StatsFilter: StatsFrom: StatsTo: StatsHost: Metric: ListFilter: ListHost: Inputs:[]}
```

It will allows us to see what is the differences between the two locations.

Thanks

Alain

**Comment by adejoux** [comment] 2017-01-16 09:05
No news and not reproductible in my environment. Closing it for now.

**Closed as completed by adejoux** 2017-01-16 09:05 UTC
Labels: enhancement
