### ISSUE TITLE
Disk graph is missed in dashboard 

### ISSUE THREAD

**Issue by adilnaimi** [adejoux/nmon2influxdb#15] opened 2015-12-24 06:33 UTC
The disk graph is missed in my dashboard 

![dashboard](https://cloud.githubusercontent.com/assets/1929963/11990572/ab281b96-aa20-11e5-89ea-eac8be6ceb40.png)

this is my `.nmon2influxdb.cfg`:

```
debug=true
timezone="Asia/Qatar"
influxdb_user="root"
influxdb_password="root"
influxdb_server="localhost"
influxdb_port="8086"
influxdb_database="nmon"
grafana_user="admin"
grafana_password="admin"
grafana_url="http://localhost:3000"
grafana_datasource="nmon2influxdb"
import_skip_disks=false
import_all_cpus=false
import_build_dashboard=true
dashboard_write_file=true
stats_limit=20
stats_sort="mean"
stats_filter=""
stats_from=""
stats_to=""
stats_host=""
```

the nmon data was uploaded successfully as well the dashboard :

```
 nmon2influxdb import aix71_test_15122*
#######################################
File aix71_test1_151223_0000.nmon imported : 398927 points !
Dashboard uploaded to grafana
###############
File aix71_test1_151224_0000.nmon imported : 157759 points !
Dashboard uploaded to grafana
```

**Comment by adejoux** [comment] 2016-01-14 09:53
Hello,

Sorry I missed your ticket. I am working on a new default dashboard using enhancements from grafana 2.6.

**Comment by adilnaimi** [comment] 2016-01-14 10:48
Hello,

Thanks for the feedback, I'm staying tuned!

**Comment by adejoux** [comment] 2016-01-14 21:06
I released a quick version now. I saw you didn't have the grouping working in your chart. I think you are using grafana 2.6. I updated the tool to support it. 

And I added the charts for disks for AIX. They are collapsed by default. In case you have too much disks on your partition, it will still load your dashboard.

Let me know if it's fixed for you :)

**Comment by adilnaimi** [comment] 2016-01-17 08:06
It works like charm!
thank you

Can I have file system size (usage) on dashboard 
also i have the TOP graph is empty

**Comment by adejoux** [comment] 2016-01-17 13:06
Great. 

I am closing this issue.

I am working on improving the default dashboard in #16. Not really hard so I hope to do it quickly :)

**Closed as completed by adejoux** 2016-01-17 13:06 UTC
Labels: enhancement

**Comment by adilnaimi** [comment] 2016-01-17 14:19
👍

**Comment by adilnaimi** [comment] 2016-01-24 10:45
I just discover the TOP graph is empty.

I'm not sure if I have missed something?

![image](https://cloud.githubusercontent.com/assets/1929963/12535809/b6bff01c-c2a0-11e5-9c8d-94ebcdc95897.png)

**Comment by adejoux** [comment] 2016-01-26 10:17
Hello,

Hard to guess the cause here. Can you send me the nmon file by email?

Alain

**Comment by adilnaimi** [comment] 2017-02-06 07:21
coming to this old issue, the TOP data fixed by simply remove `TOP` from `import_skip_metrics` in `~/.nmon2influxdb.cfg` 

I confirm closing the issue

**Comment by adejoux** [comment] 2017-02-06 08:06
good news :) TOP is adding a lot of data and muc users doesn't care so I skip it by default.

Thanks for the feedback :)
